<?php
/**
 * ReportingApi
 * PHP version 7.4
 *
 * @category Class
 * @package  ClearentReportingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Clearent Reporting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClearentReportingApi\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use ClearentReportingApi\ApiException;
use ClearentReportingApi\Configuration;
use ClearentReportingApi\HeaderSelector;
use ClearentReportingApi\ObjectSerializer;

/**
 * ReportingApi Class Doc Comment
 *
 * @category Class
 * @package  ClearentReportingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReportingApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation merchantClosedBatches
     *
     * @param  string $batch_status batch_status (optional)
     * @param  string $expected_funded_date expected_funded_date (optional)
     * @param  string $merchant_number Unique merchant number - MID Number. (optional)
     * @param  string $page_number Allows a specific page to be returned from a result list. (optional)
     * @param  string $page_size Allows setting of the number of results to be returned per page. (optional)
     * @param  string $sort_by Allows sorting of the paginated result set, multiple order by allowed. (optional)
     *
     * @throws \ClearentReportingApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ClearentReportingApi\Model\MerchantClosedBatchesResponse
     */
    public function merchantClosedBatches($batch_status = null, $expected_funded_date = null, $merchant_number = null, $page_number = null, $page_size = null, $sort_by = null)
    {
        list($response) = $this->merchantClosedBatchesWithHttpInfo($batch_status, $expected_funded_date, $merchant_number, $page_number, $page_size, $sort_by);
        return $response;
    }

    /**
     * Operation merchantClosedBatchesWithHttpInfo
     *
     * @param  string $batch_status (optional)
     * @param  string $expected_funded_date (optional)
     * @param  string $merchant_number Unique merchant number - MID Number. (optional)
     * @param  string $page_number Allows a specific page to be returned from a result list. (optional)
     * @param  string $page_size Allows setting of the number of results to be returned per page. (optional)
     * @param  string $sort_by Allows sorting of the paginated result set, multiple order by allowed. (optional)
     *
     * @throws \ClearentReportingApi\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ClearentReportingApi\Model\MerchantClosedBatchesResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function merchantClosedBatchesWithHttpInfo($batch_status = null, $expected_funded_date = null, $merchant_number = null, $page_number = null, $page_size = null, $sort_by = null)
    {
        $request = $this->merchantClosedBatchesRequest($batch_status, $expected_funded_date, $merchant_number, $page_number, $page_size, $sort_by);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            } catch (ConnectException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    (int) $e->getCode(),
                    null,
                    null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        (string) $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            switch($statusCode) {
                case 200:
                    if ('\ClearentReportingApi\Model\MerchantClosedBatchesResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\ClearentReportingApi\Model\MerchantClosedBatchesResponse' !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ClearentReportingApi\Model\MerchantClosedBatchesResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ClearentReportingApi\Model\MerchantClosedBatchesResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ClearentReportingApi\Model\MerchantClosedBatchesResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation merchantClosedBatchesAsync
     *
     * @param  string $batch_status (optional)
     * @param  string $expected_funded_date (optional)
     * @param  string $merchant_number Unique merchant number - MID Number. (optional)
     * @param  string $page_number Allows a specific page to be returned from a result list. (optional)
     * @param  string $page_size Allows setting of the number of results to be returned per page. (optional)
     * @param  string $sort_by Allows sorting of the paginated result set, multiple order by allowed. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function merchantClosedBatchesAsync($batch_status = null, $expected_funded_date = null, $merchant_number = null, $page_number = null, $page_size = null, $sort_by = null)
    {
        return $this->merchantClosedBatchesAsyncWithHttpInfo($batch_status, $expected_funded_date, $merchant_number, $page_number, $page_size, $sort_by)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation merchantClosedBatchesAsyncWithHttpInfo
     *
     * @param  string $batch_status (optional)
     * @param  string $expected_funded_date (optional)
     * @param  string $merchant_number Unique merchant number - MID Number. (optional)
     * @param  string $page_number Allows a specific page to be returned from a result list. (optional)
     * @param  string $page_size Allows setting of the number of results to be returned per page. (optional)
     * @param  string $sort_by Allows sorting of the paginated result set, multiple order by allowed. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function merchantClosedBatchesAsyncWithHttpInfo($batch_status = null, $expected_funded_date = null, $merchant_number = null, $page_number = null, $page_size = null, $sort_by = null)
    {
        $returnType = '\ClearentReportingApi\Model\MerchantClosedBatchesResponse';
        $request = $this->merchantClosedBatchesRequest($batch_status, $expected_funded_date, $merchant_number, $page_number, $page_size, $sort_by);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    if ($returnType === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'merchantClosedBatches'
     *
     * @param  string $batch_status (optional)
     * @param  string $expected_funded_date (optional)
     * @param  string $merchant_number Unique merchant number - MID Number. (optional)
     * @param  string $page_number Allows a specific page to be returned from a result list. (optional)
     * @param  string $page_size Allows setting of the number of results to be returned per page. (optional)
     * @param  string $sort_by Allows sorting of the paginated result set, multiple order by allowed. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function merchantClosedBatchesRequest($batch_status = null, $expected_funded_date = null, $merchant_number = null, $page_number = null, $page_size = null, $sort_by = null)
    {

        $resourcePath = '/data/api/v1/standard/merchantClosedBatches';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $batch_status,
            'batchStatus', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $expected_funded_date,
            'expectedFundedDate', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $merchant_number,
            'merchantNumber', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_number,
            'pageNumber', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $page_size,
            'pageSize', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $sort_by,
            'sortBy', // param base name
            'string', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);




        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('AccessKey');
        if ($apiKey !== null) {
            $headers['AccessKey'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
