<?php
/**
 * MerchantClosedBatchesResponseMerchantClosedBatchesInner
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ClearentReportingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Clearent Reporting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ClearentReportingApi\Model;

use \ArrayAccess;
use \ClearentReportingApi\ObjectSerializer;

/**
 * MerchantClosedBatchesResponseMerchantClosedBatchesInner Class Doc Comment
 *
 * @category Class
 * @package  ClearentReportingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class MerchantClosedBatchesResponseMerchantClosedBatchesInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'MerchantClosedBatchesResponse_merchantClosedBatches_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'backup_withholding' => 'float',
        'batch_fees' => 'float',
        'batch_number' => 'string',
        'batch_total' => 'float',
        'closed_date' => 'string',
        'conveyed_amount' => 'float',
        'conveyed_count' => 'float',
        'deposit_account_number' => 'float',
        'deposit_amount' => 'float',
        'funded_date' => 'string',
        'merchant_number' => 'string',
        'refund_count' => 'float',
        'refunds' => 'float',
        'sales' => 'float',
        'sales_count' => 'float',
        'settle_date' => 'string',
        'store_number' => 'string',
        'terminal_id' => 'string',
        'terminal_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'backup_withholding' => null,
        'batch_fees' => null,
        'batch_number' => null,
        'batch_total' => null,
        'closed_date' => null,
        'conveyed_amount' => null,
        'conveyed_count' => null,
        'deposit_account_number' => null,
        'deposit_amount' => null,
        'funded_date' => null,
        'merchant_number' => null,
        'refund_count' => null,
        'refunds' => null,
        'sales' => null,
        'sales_count' => null,
        'settle_date' => null,
        'store_number' => null,
        'terminal_id' => null,
        'terminal_name' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'backup_withholding' => 'backupWithholding',
        'batch_fees' => 'batchFees',
        'batch_number' => 'batchNumber',
        'batch_total' => 'batchTotal',
        'closed_date' => 'closedDate',
        'conveyed_amount' => 'conveyedAmount',
        'conveyed_count' => 'conveyedCount',
        'deposit_account_number' => 'depositAccountNumber',
        'deposit_amount' => 'depositAmount',
        'funded_date' => 'fundedDate',
        'merchant_number' => 'merchantNumber',
        'refund_count' => 'refundCount',
        'refunds' => 'refunds',
        'sales' => 'sales',
        'sales_count' => 'salesCount',
        'settle_date' => 'settleDate',
        'store_number' => 'storeNumber',
        'terminal_id' => 'terminalID',
        'terminal_name' => 'terminalName'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'backup_withholding' => 'setBackupWithholding',
        'batch_fees' => 'setBatchFees',
        'batch_number' => 'setBatchNumber',
        'batch_total' => 'setBatchTotal',
        'closed_date' => 'setClosedDate',
        'conveyed_amount' => 'setConveyedAmount',
        'conveyed_count' => 'setConveyedCount',
        'deposit_account_number' => 'setDepositAccountNumber',
        'deposit_amount' => 'setDepositAmount',
        'funded_date' => 'setFundedDate',
        'merchant_number' => 'setMerchantNumber',
        'refund_count' => 'setRefundCount',
        'refunds' => 'setRefunds',
        'sales' => 'setSales',
        'sales_count' => 'setSalesCount',
        'settle_date' => 'setSettleDate',
        'store_number' => 'setStoreNumber',
        'terminal_id' => 'setTerminalId',
        'terminal_name' => 'setTerminalName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'backup_withholding' => 'getBackupWithholding',
        'batch_fees' => 'getBatchFees',
        'batch_number' => 'getBatchNumber',
        'batch_total' => 'getBatchTotal',
        'closed_date' => 'getClosedDate',
        'conveyed_amount' => 'getConveyedAmount',
        'conveyed_count' => 'getConveyedCount',
        'deposit_account_number' => 'getDepositAccountNumber',
        'deposit_amount' => 'getDepositAmount',
        'funded_date' => 'getFundedDate',
        'merchant_number' => 'getMerchantNumber',
        'refund_count' => 'getRefundCount',
        'refunds' => 'getRefunds',
        'sales' => 'getSales',
        'sales_count' => 'getSalesCount',
        'settle_date' => 'getSettleDate',
        'store_number' => 'getStoreNumber',
        'terminal_id' => 'getTerminalId',
        'terminal_name' => 'getTerminalName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['backup_withholding'] = $data['backup_withholding'] ?? null;
        $this->container['batch_fees'] = $data['batch_fees'] ?? null;
        $this->container['batch_number'] = $data['batch_number'] ?? null;
        $this->container['batch_total'] = $data['batch_total'] ?? null;
        $this->container['closed_date'] = $data['closed_date'] ?? null;
        $this->container['conveyed_amount'] = $data['conveyed_amount'] ?? null;
        $this->container['conveyed_count'] = $data['conveyed_count'] ?? null;
        $this->container['deposit_account_number'] = $data['deposit_account_number'] ?? null;
        $this->container['deposit_amount'] = $data['deposit_amount'] ?? null;
        $this->container['funded_date'] = $data['funded_date'] ?? null;
        $this->container['merchant_number'] = $data['merchant_number'] ?? null;
        $this->container['refund_count'] = $data['refund_count'] ?? null;
        $this->container['refunds'] = $data['refunds'] ?? null;
        $this->container['sales'] = $data['sales'] ?? null;
        $this->container['sales_count'] = $data['sales_count'] ?? null;
        $this->container['settle_date'] = $data['settle_date'] ?? null;
        $this->container['store_number'] = $data['store_number'] ?? null;
        $this->container['terminal_id'] = $data['terminal_id'] ?? null;
        $this->container['terminal_name'] = $data['terminal_name'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets backup_withholding
     *
     * @return float|null
     */
    public function getBackupWithholding()
    {
        return $this->container['backup_withholding'];
    }

    /**
     * Sets backup_withholding
     *
     * @param float|null $backup_withholding Amount of backup withholding.
     *
     * @return self
     */
    public function setBackupWithholding($backup_withholding)
    {
        $this->container['backup_withholding'] = $backup_withholding;

        return $this;
    }

    /**
     * Gets batch_fees
     *
     * @return float|null
     */
    public function getBatchFees()
    {
        return $this->container['batch_fees'];
    }

    /**
     * Sets batch_fees
     *
     * @param float|null $batch_fees Amount of fees assessed on the batch.
     *
     * @return self
     */
    public function setBatchFees($batch_fees)
    {
        $this->container['batch_fees'] = $batch_fees;

        return $this;
    }

    /**
     * Gets batch_number
     *
     * @return string|null
     */
    public function getBatchNumber()
    {
        return $this->container['batch_number'];
    }

    /**
     * Sets batch_number
     *
     * @param string|null $batch_number 3 digit number of the batch for the specific merchant, store, and terminal.
     *
     * @return self
     */
    public function setBatchNumber($batch_number)
    {
        $this->container['batch_number'] = $batch_number;

        return $this;
    }

    /**
     * Gets batch_total
     *
     * @return float|null
     */
    public function getBatchTotal()
    {
        return $this->container['batch_total'];
    }

    /**
     * Sets batch_total
     *
     * @param float|null $batch_total Net amount of the batch.
     *
     * @return self
     */
    public function setBatchTotal($batch_total)
    {
        $this->container['batch_total'] = $batch_total;

        return $this;
    }

    /**
     * Gets closed_date
     *
     * @return string|null
     */
    public function getClosedDate()
    {
        return $this->container['closed_date'];
    }

    /**
     * Sets closed_date
     *
     * @param string|null $closed_date Date and time batch was closed.
     *
     * @return self
     */
    public function setClosedDate($closed_date)
    {
        $this->container['closed_date'] = $closed_date;

        return $this;
    }

    /**
     * Gets conveyed_amount
     *
     * @return float|null
     */
    public function getConveyedAmount()
    {
        return $this->container['conveyed_amount'];
    }

    /**
     * Sets conveyed_amount
     *
     * @param float|null $conveyed_amount Total conveyed amount.
     *
     * @return self
     */
    public function setConveyedAmount($conveyed_amount)
    {
        $this->container['conveyed_amount'] = $conveyed_amount;

        return $this;
    }

    /**
     * Gets conveyed_count
     *
     * @return float|null
     */
    public function getConveyedCount()
    {
        return $this->container['conveyed_count'];
    }

    /**
     * Sets conveyed_count
     *
     * @param float|null $conveyed_count Number of conveyed transactions.
     *
     * @return self
     */
    public function setConveyedCount($conveyed_count)
    {
        $this->container['conveyed_count'] = $conveyed_count;

        return $this;
    }

    /**
     * Gets deposit_account_number
     *
     * @return float|null
     */
    public function getDepositAccountNumber()
    {
        return $this->container['deposit_account_number'];
    }

    /**
     * Sets deposit_account_number
     *
     * @param float|null $deposit_account_number The Merchants bank account number.
     *
     * @return self
     */
    public function setDepositAccountNumber($deposit_account_number)
    {
        $this->container['deposit_account_number'] = $deposit_account_number;

        return $this;
    }

    /**
     * Gets deposit_amount
     *
     * @return float|null
     */
    public function getDepositAmount()
    {
        return $this->container['deposit_amount'];
    }

    /**
     * Sets deposit_amount
     *
     * @param float|null $deposit_amount Amount deposited into Merchant's account.
     *
     * @return self
     */
    public function setDepositAmount($deposit_amount)
    {
        $this->container['deposit_amount'] = $deposit_amount;

        return $this;
    }

    /**
     * Gets funded_date
     *
     * @return string|null
     */
    public function getFundedDate()
    {
        return $this->container['funded_date'];
    }

    /**
     * Sets funded_date
     *
     * @param string|null $funded_date Date funding was expected to be made to the merchant.
     *
     * @return self
     */
    public function setFundedDate($funded_date)
    {
        $this->container['funded_date'] = $funded_date;

        return $this;
    }

    /**
     * Gets merchant_number
     *
     * @return string|null
     */
    public function getMerchantNumber()
    {
        return $this->container['merchant_number'];
    }

    /**
     * Sets merchant_number
     *
     * @param string|null $merchant_number Merchant MID Number.
     *
     * @return self
     */
    public function setMerchantNumber($merchant_number)
    {
        $this->container['merchant_number'] = $merchant_number;

        return $this;
    }

    /**
     * Gets refund_count
     *
     * @return float|null
     */
    public function getRefundCount()
    {
        return $this->container['refund_count'];
    }

    /**
     * Sets refund_count
     *
     * @param float|null $refund_count Number of refund transactions.
     *
     * @return self
     */
    public function setRefundCount($refund_count)
    {
        $this->container['refund_count'] = $refund_count;

        return $this;
    }

    /**
     * Gets refunds
     *
     * @return float|null
     */
    public function getRefunds()
    {
        return $this->container['refunds'];
    }

    /**
     * Sets refunds
     *
     * @param float|null $refunds Total refund amount.
     *
     * @return self
     */
    public function setRefunds($refunds)
    {
        $this->container['refunds'] = $refunds;

        return $this;
    }

    /**
     * Gets sales
     *
     * @return float|null
     */
    public function getSales()
    {
        return $this->container['sales'];
    }

    /**
     * Sets sales
     *
     * @param float|null $sales Total sales amount.
     *
     * @return self
     */
    public function setSales($sales)
    {
        $this->container['sales'] = $sales;

        return $this;
    }

    /**
     * Gets sales_count
     *
     * @return float|null
     */
    public function getSalesCount()
    {
        return $this->container['sales_count'];
    }

    /**
     * Sets sales_count
     *
     * @param float|null $sales_count Number of sales transactions in the batch.
     *
     * @return self
     */
    public function setSalesCount($sales_count)
    {
        $this->container['sales_count'] = $sales_count;

        return $this;
    }

    /**
     * Gets settle_date
     *
     * @return string|null
     */
    public function getSettleDate()
    {
        return $this->container['settle_date'];
    }

    /**
     * Sets settle_date
     *
     * @param string|null $settle_date Date the batch was settled.
     *
     * @return self
     */
    public function setSettleDate($settle_date)
    {
        $this->container['settle_date'] = $settle_date;

        return $this;
    }

    /**
     * Gets store_number
     *
     * @return string|null
     */
    public function getStoreNumber()
    {
        return $this->container['store_number'];
    }

    /**
     * Sets store_number
     *
     * @param string|null $store_number 4-digit store identification number representing the store where the terminal is located.
     *
     * @return self
     */
    public function setStoreNumber($store_number)
    {
        $this->container['store_number'] = $store_number;

        return $this;
    }

    /**
     * Gets terminal_id
     *
     * @return string|null
     */
    public function getTerminalId()
    {
        return $this->container['terminal_id'];
    }

    /**
     * Sets terminal_id
     *
     * @param string|null $terminal_id 4-digit number assigned to a terminal.
     *
     * @return self
     */
    public function setTerminalId($terminal_id)
    {
        $this->container['terminal_id'] = $terminal_id;

        return $this;
    }

    /**
     * Gets terminal_name
     *
     * @return string|null
     */
    public function getTerminalName()
    {
        return $this->container['terminal_name'];
    }

    /**
     * Sets terminal_name
     *
     * @param string|null $terminal_name Customer specified name for the terminal.
     *
     * @return self
     */
    public function setTerminalName($terminal_name)
    {
        $this->container['terminal_name'] = $terminal_name;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


