<?php
/**
 * MerchantClosedBatches200ResponsePageTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ClearentReportingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Clearent Reporting API
 *
 * Clearent API written by the members of Dental Intelligence.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ClearentReportingApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MerchantClosedBatches200ResponsePageTest Class Doc Comment
 *
 * @category    Class
 * @description MerchantClosedBatches200ResponsePage
 * @package     ClearentReportingApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MerchantClosedBatches200ResponsePageTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MerchantClosedBatches200ResponsePage"
     */
    public function testMerchantClosedBatches200ResponsePage()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "last"
     */
    public function testPropertyLast()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "number"
     */
    public function testPropertyNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "size"
     */
    public function testPropertySize()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "total_elements"
     */
    public function testPropertyTotalElements()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
