<?php
/**
 * MerchantClosedBatches200ResponseMerchantClosedBatchesInnerTest
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  ClearentReportingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Clearent Reporting API
 *
 * Clearent API written by the members of Dental Intelligence.
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ClearentReportingApi\Test\Model;

use PHPUnit\Framework\TestCase;

/**
 * MerchantClosedBatches200ResponseMerchantClosedBatchesInnerTest Class Doc Comment
 *
 * @category    Class
 * @description MerchantClosedBatches200ResponseMerchantClosedBatchesInner
 * @package     ClearentReportingApi
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class MerchantClosedBatches200ResponseMerchantClosedBatchesInnerTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "MerchantClosedBatches200ResponseMerchantClosedBatchesInner"
     */
    public function testMerchantClosedBatches200ResponseMerchantClosedBatchesInner()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "backup_withholding"
     */
    public function testPropertyBackupWithholding()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "batch_fees"
     */
    public function testPropertyBatchFees()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "batch_number"
     */
    public function testPropertyBatchNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "batch_total"
     */
    public function testPropertyBatchTotal()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "closed_date"
     */
    public function testPropertyClosedDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "conveyed_amount"
     */
    public function testPropertyConveyedAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "conveyed_count"
     */
    public function testPropertyConveyedCount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "deposit_account_number"
     */
    public function testPropertyDepositAccountNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "deposit_amount"
     */
    public function testPropertyDepositAmount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "funded_date"
     */
    public function testPropertyFundedDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "merchant_number"
     */
    public function testPropertyMerchantNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "refund_count"
     */
    public function testPropertyRefundCount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "refunds"
     */
    public function testPropertyRefunds()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "row_number"
     */
    public function testPropertyRowNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sales"
     */
    public function testPropertySales()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "sales_count"
     */
    public function testPropertySalesCount()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "settle_date"
     */
    public function testPropertySettleDate()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "store_number"
     */
    public function testPropertyStoreNumber()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "terminal_id"
     */
    public function testPropertyTerminalId()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }

    /**
     * Test attribute "terminal_name"
     */
    public function testPropertyTerminalName()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
