<?php
/**
 * ReportingApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  ClearentReportingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Clearent Reporting API
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 6.1.0-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace ClearentReportingApi\Test\Api;

use \ClearentReportingApi\Configuration;
use \ClearentReportingApi\ApiException;
use \ClearentReportingApi\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ReportingApiTest Class Doc Comment
 *
 * @category Class
 * @package  ClearentReportingApi
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ReportingApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for merchantClosedBatches
     *
     * .
     *
     */
    public function testMerchantClosedBatches()
    {
        // TODO: implement
        $this->markTestIncomplete('Not implemented');
    }
}
